package com.blog.model;
// Generated 2017-4-2 12:37:59 by Hibernate Tools 5.2.1.Final

/**
 * BllAttachment generated by hbm2java
 */
public class BllAttachment implements java.io.Serializable {

	private String id;
	private String attName;
	private String attPath;
	private String articleId;
	private Integer attSize;

	public BllAttachment() {
	}

	public BllAttachment(String id) {
		this.id = id;
	}

	public BllAttachment(String id, String attName, String attPath, String articleId, Integer attSize) {
		this.id = id;
		this.attName = attName;
		this.attPath = attPath;
		this.articleId = articleId;
		this.attSize = attSize;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getAttName() {
		return this.attName;
	}

	public void setAttName(String attName) {
		this.attName = attName;
	}

	public String getAttPath() {
		return this.attPath;
	}

	public void setAttPath(String attPath) {
		this.attPath = attPath;
	}

	public String getArticleId() {
		return this.articleId;
	}

	public void setArticleId(String articleId) {
		this.articleId = articleId;
	}

	public Integer getAttSize() {
		return this.attSize;
	}

	public void setAttSize(Integer attSize) {
		this.attSize = attSize;
	}

}
