package com.blog.model;
// Generated 2017-4-2 12:37:59 by Hibernate Tools 5.2.1.Final

import java.util.Date;

import org.codehaus.jackson.map.annotate.JsonSerialize;

import com.blog.utils.CustomDateSerializer;

/**
 * BllCommont generated by hbm2java
 */
public class BllCommont implements java.io.Serializable {

	private String id;
	private String articleId;
	private String person;
	private String comContent;
	private Date comTime;
	private String comEmail;

	public BllCommont() {
	}

	public BllCommont(String id) {
		this.id = id;
	}

	public BllCommont(String id, String articleId, String person, String comContent, Date comTime, String comEmail) {
		this.id = id;
		this.articleId = articleId;
		this.person = person;
		this.comContent = comContent;
		this.comTime = comTime;
		this.comEmail = comEmail;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getArticleId() {
		return this.articleId;
	}

	public void setArticleId(String articleId) {
		this.articleId = articleId;
	}

	public String getPerson() {
		return this.person;
	}

	public void setPerson(String person) {
		this.person = person;
	}

	public String getComContent() {
		return this.comContent;
	}

	public void setComContent(String comContent) {
		this.comContent = comContent;
	}

	@JsonSerialize(using = CustomDateSerializer.class)
	public Date getComTime() {
		return this.comTime;
	}

	@JsonSerialize(using = CustomDateSerializer.class)
	public void setComTime(Date comTime) {
		this.comTime = comTime;
	}

	public String getComEmail() {
		return this.comEmail;
	}

	public void setComEmail(String comEmail) {
		this.comEmail = comEmail;
	}

}
