package com.blog.model;
// Generated 2017-4-2 12:37:59 by Hibernate Tools 5.2.1.Final

/**
 * BllFavarticle generated by hbm2java
 */
public class BllFavarticle implements java.io.Serializable {

	private String id;
	private String user;
	private String articleTitle;
	private String describle;
	private String articleUrl;

	public BllFavarticle() {
	}

	public BllFavarticle(String id) {
		this.id = id;
	}

	public BllFavarticle(String id, String user, String articleTitle, String describle, String articleUrl) {
		this.id = id;
		this.user = user;
		this.articleTitle = articleTitle;
		this.describle = describle;
		this.articleUrl = articleUrl;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	public String getArticleTitle() {
		return this.articleTitle;
	}

	public void setArticleTitle(String articleTitle) {
		this.articleTitle = articleTitle;
	}

	public String getDescrible() {
		return this.describle;
	}

	public void setDescrible(String describle) {
		this.describle = describle;
	}

	public String getArticleUrl() {
		return this.articleUrl;
	}

	public void setArticleUrl(String articleUrl) {
		this.articleUrl = articleUrl;
	}

}
