package com.blog.model;
// Generated 2017-4-2 12:37:59 by Hibernate Tools 5.2.1.Final

/**
 * BllFavuser generated by hbm2java
 */
public class BllFavuser implements java.io.Serializable {

	private String id;
	private String user;
	private String favUser;
	private String describle;

	public BllFavuser() {
	}

	public BllFavuser(String id) {
		this.id = id;
	}

	public BllFavuser(String id, String user, String favUser, String describle) {
		this.id = id;
		this.user = user;
		this.favUser = favUser;
		this.describle = describle;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	public String getFavUser() {
		return this.favUser;
	}

	public void setFavUser(String favUser) {
		this.favUser = favUser;
	}

	public String getDescrible() {
		return this.describle;
	}

	public void setDescrible(String describle) {
		this.describle = describle;
	}

}
