package com.blog.model;
// Generated 2017-4-2 12:37:59 by Hibernate Tools 5.2.1.Final

/**
 * BllSuggest generated by hbm2java
 */
public class BllSuggest implements java.io.Serializable {

	private String id;
	private String user;
	private String articleId;
	private String articleTitle;

	public BllSuggest() {
	}

	public BllSuggest(String id) {
		this.id = id;
	}

	public BllSuggest(String id, String user, String articleId) {
		this.id = id;
		this.user = user;
		this.articleId = articleId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	public String getArticleId() {
		return this.articleId;
	}

	public void setArticleId(String articleId) {
		this.articleId = articleId;
	}

	public String getArticleTitle() {
		return articleTitle;
	}

	public void setArticleTitle(String articleTitle) {
		this.articleTitle = articleTitle;
	}

}
