package com.blog.model;

import java.util.Date;

// Generated 2017-4-2 12:37:59 by Hibernate Tools 5.2.1.Final

/**
 * SysUsers generated by hbm2java
 */
public class SysUsers implements java.io.Serializable {

	//id和usercode都是唯一的，id是主键。看实际情况决定使用哪个
	private String id;
	private String userCode;
	private String userPassword;
	private String userName;
	private String email;
	private String photoPath;
	private String photoFingerPrint;
	private Date createTime;
	private Date modifiedTime;
	private String creator;
	private String modifiedtor;

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUserCode() {
		return this.userCode;
	}

	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}

	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhotoPath() {
		return photoPath;
	}

	public void setPhotoPath(String photoPath) {
		this.photoPath = photoPath;
	}

	public String getPhotoFingerPrint() {
		return photoFingerPrint;
	}

	public void setPhotoFingerPrint(String photoFingerPrint) {
		this.photoFingerPrint = photoFingerPrint;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getModifiedTime() {
		return modifiedTime;
	}

	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	public String getCreator() {
		return creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public String getModifiedtor() {
		return modifiedtor;
	}

	public void setModifiedtor(String modifiedtor) {
		this.modifiedtor = modifiedtor;
	}
}
