package com.blog.model;
// Generated 2017-4-2 12:37:59 by Hibernate Tools 5.2.1.Final

/**
 * SysUsers generated by hbm2java
 */
public class SysUsers implements java.io.Serializable {

	private String userCode;
	private String id;
	private String userPassword;
	private String userName;
	private String email;

	public SysUsers() {
	}

	public SysUsers(String userCode) {
		this.userCode = userCode;
	}

	public SysUsers(String userCode, String id, String userPassword, String userName, String email) {
		this.userCode = userCode;
		this.id = id;
		this.userPassword = userPassword;
		this.userName = userName;
		this.email = email;
	}

	public String getUserCode() {
		return this.userCode;
	}

	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
